package enums;

public enum ContentType {
	TEXT_PLAIN,
	TEXT_HTML,
	TEXT_CSS,
	TEXT_JAVASCRIPT,
	IMAGE_GIF,
	IMAGE_PNG,
	IMAGE_JPEG,
	IMAGE_BMP,
	IMAGE_WEBP,
	AUDIO_MIDI,
	AUDIO_MPEG,
	AUDIO_WEBM,
	AUDIO_OGG,
	AUDIO_WAV,
	VIDEO_WEBM,
	VIDEO_OGG,
	APPLICATION_OCTET_STREAM,
	APPLICATION_PKCS12,
	APPLICATION_VND_MSPOWERPOINT,
	APPLICATION_XHTML_XML,
	APPLICATION_XML,
	APPLICATION_PDF
}
